export const NOT_FOUND_INPUT_VALUE = "NOT_FOUND_INPUT_VALUE"
export const NOT_FOUND_TRIGGER_COMMANDS_ARGUMENT = "NOT_FOUND_TRIGGER_COMMANDS_ARGUMENT"
export const NOT_HAVE_LOGIC = "NOT_HAVE_LOGIC"
export const ARRAY_NOT_HAVE_OCCURS_ODD_TIME = "ARRAY_NOT_HAVE_OCCURS_ODD_TIME"